version: 2.1
jobs:
  build:
  working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3 
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

       run: # run tests
          name: test
          command: npm test 